### PR TITLE
Get country code and region code automatically

### PR DESCRIPTION
**Pull request by Elema82**

### CODE REVIEW

**Comment by MageSuper** [comment]
Just tested it, and it is not working, getting this error:

Uncaught TypeError: Cannot read property 'split' of undefined abstract.js

**Comment by manuelcanepa** [comment]
@MageSuper Can you give us a trace? What change of this PR affect that abstract?

**Comment by MageSuper** [comment]
@manuelcanepa Although the old code version still working fine.

```
Uncaught TypeError: Cannot read property 'split' of undefined >>>>>>> abstract.js:125 
    at UiClass.initConfig (abstract.js:125)
    at UiClass.initConfig (wrapper.js:109)
    at UiClass.initialize (class.js:70)
    at UiClass._super (wrapper.js:106)
    at UiClass.initialize (element.js:103)
    at UiClass.initialize (wrapper.js:109)
    at UiClass._super (wrapper.js:106)
    at UiClass.initialize (abstract.js:76)
    at UiClass.initialize (wrapper.js:109)
    at UiClass._super (wrapper.js:106)
```

**Comment by MageSuper** [comment]
@manuelcanepa https://prnt.sc/rd0mra

**Comment by manuelcanepa** [comment]
@MageSuper  Im just installed on a Magento 2 Vanilla server and its working. This PR just make dinamic selection of country and region instead of static Romania country. I cant reproduce your bug.

**Comment by manuelcanepa** [comment]
BTW: You need to edit the last version of "module.xml" see #71

**Pull request closed without merging**
